version: '3.8'
services:
  trainingdb_service:
    image: jads8/trainingdbapi:0.0.1
    environment:
      - DB_URL=sqlite:///features.db
    networks:
      - training-pipeline
    ports:
      - "5000:5000"

  training_service:
    image: jads8/trainapi:0.0.1
    depends_on:
      - trainingdb_service
    environment:
      - TRAININGDB_API=http://trainingdb_service:5000/training-db/diabetes
      - MODEL_REPO=model_repo_jads8
      - PROJECT_ID=10.128.0.7
    networks:
      - training-pipeline
    ports:
      - "5001:5000"

  prediction_service:
    image: jads8/predictionapi:0.0.1
    depends_on:
      - training_service
    environment:
      - MODEL_REPO=model_repo_jads8
      - PROJECT_ID=10.128.0.7
    networks:
      - prediction-pipeline
    ports:
      - "5002:5000"

  visualization_service:
    image: jads8/visualization:0.0.1
    depends_on:
      - training_service
    environment:
      - MODEL_REPO=model_repo_jads8
      - PROJECT_ID=10.128.0.7
    networks:
      - visualization-pipeline
    ports:
      - "5003:5000"

  sample_service:
    image: jads8/sample:0.0.1
    depends_on:
      - prediction_service
    environment:
      - MODEL_REPO=model_repo_jads8
      - PROJECT_ID=10.128.0.7
    networks:
      - sample-pipeline
    ports:
      - "5004:5000"

networks:
  training-pipeline:
    driver: overlay
  prediction-pipeline:
    driver: overlay
  visualization-pipeline:
    driver: overlay
  sample-pipeline:
    driver: overlay